const Course = 
exports.section = async(req,res) =>{

    try{

    }
    catch(error){
        return res.status(400).json({
            succes:false,
            message:"Somthing went wrong while creating course"
        })
    }
}